// Mocks generated by Mockito 5.4.6 from annotations
// in sixam_mart_delivery/test/unit/order_controller_bugs_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:get/get.dart' as _i2;
import 'package:image_picker/image_picker.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sixam_mart_delivery/api/api_client.dart' as _i9;
import 'package:sixam_mart_delivery/common/models/response_model.dart' as _i3;
import 'package:sixam_mart_delivery/features/order/domain/models/ignore_model.dart'
    as _i11;
import 'package:sixam_mart_delivery/features/order/domain/models/order_cancellation_body.dart'
    as _i6;
import 'package:sixam_mart_delivery/features/order/domain/models/order_count_model.dart'
    as _i14;
import 'package:sixam_mart_delivery/features/order/domain/models/order_details_model.dart'
    as _i10;
import 'package:sixam_mart_delivery/features/order/domain/models/order_model.dart'
    as _i7;
import 'package:sixam_mart_delivery/features/order/domain/models/parcel_cancellation_reasons_model.dart'
    as _i13;
import 'package:sixam_mart_delivery/features/order/domain/models/update_status_body_model.dart'
    as _i8;
import 'package:sixam_mart_delivery/features/order/domain/services/order_service_interface.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponseModel_1 extends _i1.SmartFake implements _i3.ResponseModel {
  _FakeResponseModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OrderServiceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderServiceInterface extends _i1.Mock
    implements _i4.OrderServiceInterface {
  MockOrderServiceInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.CancellationData>?> getCancelReasons() =>
      (super.noSuchMethod(
            Invocation.method(#getCancelReasons, []),
            returnValue: _i5.Future<List<_i6.CancellationData>?>.value(),
          )
          as _i5.Future<List<_i6.CancellationData>?>);

  @override
  _i5.Future<_i2.Response<dynamic>> getOrderWithId(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderWithId, [orderId]),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(#getOrderWithId, [orderId]),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i7.PaginatedOrderModel?> getCompletedOrderList(
    int? offset, {
    String? orderStatus = 'all',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCompletedOrderList,
              [offset],
              {#orderStatus: orderStatus},
            ),
            returnValue: _i5.Future<_i7.PaginatedOrderModel?>.value(),
          )
          as _i5.Future<_i7.PaginatedOrderModel?>);

  @override
  _i5.Future<_i7.PaginatedOrderModel?> getCurrentOrders(
    int? offset, {
    String? orderStatus = 'all',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCurrentOrders,
              [offset],
              {#orderStatus: orderStatus},
            ),
            returnValue: _i5.Future<_i7.PaginatedOrderModel?>.value(),
          )
          as _i5.Future<_i7.PaginatedOrderModel?>);

  @override
  _i5.Future<List<_i7.OrderModel>?> getLatestOrders({
    bool includeRejected = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getLatestOrders,
              [],
              {#includeRejected: includeRejected},
            ),
            returnValue: _i5.Future<List<_i7.OrderModel>?>.value(),
          )
          as _i5.Future<List<_i7.OrderModel>?>);

  @override
  _i5.Future<_i3.ResponseModel> updateOrderStatus(
    _i8.UpdateStatusBodyModel? updateStatusBody,
    List<_i9.MultipartBody>? proofAttachment,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderStatus, [
              updateStatusBody,
              proofAttachment,
            ]),
            returnValue: _i5.Future<_i3.ResponseModel>.value(
              _FakeResponseModel_1(
                this,
                Invocation.method(#updateOrderStatus, [
                  updateStatusBody,
                  proofAttachment,
                ]),
              ),
            ),
          )
          as _i5.Future<_i3.ResponseModel>);

  @override
  _i5.Future<_i3.ResponseModel> ignoreOrderApi(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#ignoreOrderApi, [orderId]),
            returnValue: _i5.Future<_i3.ResponseModel>.value(
              _FakeResponseModel_1(
                this,
                Invocation.method(#ignoreOrderApi, [orderId]),
              ),
            ),
          )
          as _i5.Future<_i3.ResponseModel>);

  @override
  _i5.Future<List<_i10.OrderDetailsModel>?> getOrderDetails(int? orderID) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderDetails, [orderID]),
            returnValue: _i5.Future<List<_i10.OrderDetailsModel>?>.value(),
          )
          as _i5.Future<List<_i10.OrderDetailsModel>?>);

  @override
  _i5.Future<_i3.ResponseModel> acceptOrder(int? orderID) =>
      (super.noSuchMethod(
            Invocation.method(#acceptOrder, [orderID]),
            returnValue: _i5.Future<_i3.ResponseModel>.value(
              _FakeResponseModel_1(
                this,
                Invocation.method(#acceptOrder, [orderID]),
              ),
            ),
          )
          as _i5.Future<_i3.ResponseModel>);

  @override
  List<_i11.IgnoreModel> getIgnoreList() =>
      (super.noSuchMethod(
            Invocation.method(#getIgnoreList, []),
            returnValue: <_i11.IgnoreModel>[],
          )
          as List<_i11.IgnoreModel>);

  @override
  void setIgnoreList(List<_i11.IgnoreModel>? ignoreList) => super.noSuchMethod(
    Invocation.method(#setIgnoreList, [ignoreList]),
    returnValueForMissingStub: null,
  );

  @override
  List<_i7.OrderModel> processLatestOrders(
    List<_i7.OrderModel>? latestOrderList,
    List<int?>? ignoredIdList,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#processLatestOrders, [
              latestOrderList,
              ignoredIdList,
            ]),
            returnValue: <_i7.OrderModel>[],
          )
          as List<_i7.OrderModel>);

  @override
  List<int?> prepareIgnoreIdList(List<_i11.IgnoreModel>? ignoredRequests) =>
      (super.noSuchMethod(
            Invocation.method(#prepareIgnoreIdList, [ignoredRequests]),
            returnValue: <int?>[],
          )
          as List<int?>);

  @override
  List<_i11.IgnoreModel> tempList(
    DateTime? currentTime,
    List<_i11.IgnoreModel>? ignoredRequests,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#tempList, [currentTime, ignoredRequests]),
            returnValue: <_i11.IgnoreModel>[],
          )
          as List<_i11.IgnoreModel>);

  @override
  List<_i9.MultipartBody> prepareOrderProofImages(
    List<_i12.XFile>? pickedPrescriptions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#prepareOrderProofImages, [pickedPrescriptions]),
            returnValue: <_i9.MultipartBody>[],
          )
          as List<_i9.MultipartBody>);

  @override
  List<_i9.MultipartBody> prepareCancelEvidenceImages(
    List<_i12.XFile>? cancelEvidenceFiles,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#prepareCancelEvidenceImages, [
              cancelEvidenceFiles,
            ]),
            returnValue: <_i9.MultipartBody>[],
          )
          as List<_i9.MultipartBody>);

  @override
  _i5.Future<_i13.ParcelCancellationReasonsModel?>
  getParcelCancellationReasons({required bool? isBeforePickup}) =>
      (super.noSuchMethod(
            Invocation.method(#getParcelCancellationReasons, [], {
              #isBeforePickup: isBeforePickup,
            }),
            returnValue:
                _i5.Future<_i13.ParcelCancellationReasonsModel?>.value(),
          )
          as _i5.Future<_i13.ParcelCancellationReasonsModel?>);

  @override
  _i5.Future<bool> addParcelReturnDate({
    required int? orderId,
    required String? returnDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addParcelReturnDate, [], {
              #orderId: orderId,
              #returnDate: returnDate,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> submitParcelReturn({
    required int? orderId,
    required String? orderStatus,
    required int? returnOtp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitParcelReturn, [], {
              #orderId: orderId,
              #orderStatus: orderStatus,
              #returnOtp: returnOtp,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<_i14.OrderCountModel>?> getOrderCount(String? type) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderCount, [type]),
            returnValue: _i5.Future<List<_i14.OrderCountModel>?>.value(),
          )
          as _i5.Future<List<_i14.OrderCountModel>?>);

  @override
  _i5.Future<void> logCustomerCallAttempt({
    required int? orderId,
    required int? attemptNumber,
    required int? confirmedAtMs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logCustomerCallAttempt, [], {
              #orderId: orderId,
              #attemptNumber: attemptNumber,
              #confirmedAtMs: confirmedAtMs,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
